config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'tech-news', to: 'home#tech_news'

  resources :topics, only: [:index, :show]

  resources :blogs do
    member do
      post :toggle_status
    end
  end

  resources :portfolioos, except: [:index, :new, :show]
  get 'ror', to: 'portfolioos#ruby'
  get '/portfolio', to: 'portfolioos#index', as: 'portfolio'
  get '/portfolio/new', to: 'portfolioos#new', as: 'new_portfolio'
  get 'portfolio/:id', to: 'portfolioos#show', as: 'portfolio_show'

  devise_for :users, path: '', path_names: { sign_in: 'login',
  sign_out: 'logout', sign_up: 'register'}

end

app/models/portfolioo.rb
class Portfolioo < ActiveRecord::Base
belongs_to :user
validates_presence_of :title, :subtitle, :body, :main_image



  #Custom Scope (need to create route with it)
  def self.ROR
    where(subtitle: 'ROR')
  end

  #or

  scope :ruby_on_rails, -> {
    where(subtitle: 'ROR')
  }

  mount_uploader :main_image, PictureUploader


  #If nothing is passed for main image or thumb image, these will be the
  #defaults
  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= "http://placehold.it/200x200"
    self.thumb_image ||= "http://placehold.it/200x200"
  end


  def self.two_portfolios
    limit(2)
  end

  def self.recent
    order("created_at DESC")
  end

end

app/controllers/portfolioos_controller.rb
class PortfolioosController < ApplicationController
  #instead of application.html.erb, it uses portfolio.html.erb
  layout "portfolio"
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @portfolios = Portfolioo.recent.all
    # @portfolio = Portfolioo.paginate(page: params[:page], per_page: 5)
    @page_title = "Portfolio | Home"
  end

  def ruby
    @portfolio = Portfolioo.ruby_on_rails
  end

  def new
    @portfolio = Portfolioo.new
    @page_title = "Portfolio | New"
  end
  #Posts an article from (articles/new)
  def create
    #render plain: params[:article].inspect
    @portfolio = Portfolioo.new(portfolio_params)
    # @article.user = current_user
    if @portfolio.save
        flash[:notice] = "Article was successfully created"
        redirect_to portfolio_path
    else
      render :new
    end
  end

  def edit
    # @portfolio = Portfolioo.find(params[:id])
  end

  #no template
  def update
    # @portfolio = Portfolioo.find(params[:id])
    if @portfolio.update(portfolio_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to portfolio_path
    else
      render :edit
    end
  end

  def show
    # @portfolio = Portfolioo.find(params[:id])
  end

  #no template
  def destroy
    # @portfolio = Portfolioo.find(params[:id])
    @portfolio.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to portfolio_path
  end


  private
  #method to add data to the database
    def portfolio_params
      params.require(:portfolioo).permit(:title,
                                         :subtitle,
                                         :body,
                                         :main_image)

    end

  def set_portfolio_item
    @portfolio = Portfolioo.find(params[:id])
  end



end

app/helpers/portfolioos_helper.rb
module PortfolioosHelper
  def sample_helper
    content_tag(:h3, "My H3 tag application helper", class: "my-class")
  end

  def login_helper style = ''
     #if current user is a guest user, show register and login links
     if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path, class: style) + " ".html_safe + (link_to "Login", new_user_session_path, class: style)
     else
      (link_to "Logout", destroy_user_session_path, method: :delete, class: style) + " ".html_safe + (link_to "Edit", edit_user_registration_path, class: style)
     end
  end

  def nav_helper style, tag_type
nav_links = <<NAV
<#{tag_type}><a href="#{tech_news_path}" class="#{style}">Tech News</a></#{tag_type}>
NAV
    nav_links.html_safe
  end

def alerts
  alert = (flash[:alert] || flash[:error] || flash[:notice])

  if alert
    alert_generator alert
  end

end

def alert_generator msg
  js add_gritter(msg, title: "Stebs Portfolio", sticky:false)
end

end

app/views/portfolioos/_form.html.erb
<%= form_for(@portfolio) do |f| %>

  <% if @portfolio.errors.any? %>
    <% @portfolio.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class:'form-control', rows: 20 %>
  </div>

  <div class="form-group">
    <%= f.file_field :main_image, :class => 'form-control' %>
  </div>

  <!-- <div class="form-group">
    <%= f.file_field :thumb_image, :class => 'form-control' %>
  </div> -->

  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/portfolioos/_portfolio.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"> </h2>
  <p class="blog-post-meta"> Created: <%= distance_of_time_in_words(portfolio.inspect, Time.now) %> ago </p>
  <p class="blog-post-meta">
    <td><%= link_to "Show", portfolio_show_path(portfolio) %></td> /
    <td><%= link_to "Edit", edit_portfolioo_path(portfolio) if logged_in?(:site_admin) %></td> /
    <td><%= link_to "Delete", portfolioo_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>
  <p><%= portfolio.body %></p>

</div>

app/views/portfolioos/edit.html.erb
<div class="col-sm-8 blog-main">

  <td><%= link_to "Show", portfolio_show_path(@portfolio), class:'btn btn-primary' %></td>
  <td><%= link_to "Edit", edit_portfolioo_path(@portfolio), class:'btn btn-success' %></td>

  <%= render 'form' %>

</div>

app/views/portfolioos/index.html.erb
<div class="text-center">




<h1>Listing Portfolios</h1>

<a href="portfolio/new"> Create New Item </a></br><br>

<!-- <%= link_to "Create New Item", new_portfolio_path %> </a></br><br>
<%= new_portfolio_path %> </a></br><br>
<%= new_portfolio_url %> </a></br><br> -->


<%= render partial: 'portfolio', collection: @portfolios %>




<div class="album text-muted">
  <div class="container">
      <div class="row">
          <div class="card">
            <% @portfolios.each do |portfolio_item| %>
            <%= image_tag portfolio_item.main_image unless portfolio_item.main_image.nil? %>
            <span class="card-text">  <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item)  %> </span> <%= portfolio_item.subtitle %>
            <% end %>
          </div>
      </div>
  </div>
</div>




<br>

app/views/portfolioos/new.html.erb
<div class="col-sm-8 blog-main">
  <%= render 'form' %>
</div>

app/views/portfolioos/ruby.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<a href="portfolio/new"> Create New Item </a></br><br>

<%= link_to "Create New Item", new_portfolio_path %> </a></br><br>
<%= new_portfolio_path %> </a></br><br>
<%= new_portfolio_url %> </a></br><br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Subtitle</th>
      <th>Main Image</th>
      <th>Thumb Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio.each do |portfolio_item| %>
      <tr>
        <td><%= portfolio_item.title %></td>
        <td><%= portfolio_item.subtitle %></td>
        <td><%= portfolio_item.body %></td>
        <td><%= image_tag portfolio_item.main_image unless portfolio_item.main_image.nil? %></td>
        <td><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></td>
        <td><%= link_to "Show", portfolio_show_path(portfolio_item) %></td>
        <td><%= link_to "Edit", edit_portfolioo_path(portfolio_item) %></td>
        <td><a href="/portfolioos/<%= portfolio_item.id %>/edit"> Edit Two</a></td>
        <td><%= link_to "Delete", portfolioo_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/portfolioos/show.html.erb
<h1 class="text-center"> Show Page </h1>
<br><br>
<!-- <%= @portfolio.inspect %> <br> -->
<!-- <%= image_tag @portfolio.main_image unless @portfolio.main_image.nil?  %> <br>
<%= image_tag @portfolio.thumb_image unless @portfolio.thumb_image.nil?  %> <br>
<%= @portfolio.title %> <br>
<%= @portfolio.subtitle %> <br>
<%= @portfolio.body%> <br> -->




<!-- <div class="col-sm-8 blog-main">
  <h2><%= @portfolio.title %></h2>

  <%= link_to "Edit", edit_portfolioo_path(@portfolio) if logged_in?(:site_admin) %>

  <p>
    <%= @portfolio.body %>
  </p>

</div> -->


<div class="container">
 <div class="row">
  <div class="col-md-3">
    <%= image_tag @portfolio.main_image unless @portfolio.main_image.nil?  %>
  </div>
  <div class="col-md-3">
    <%= image_tag @portfolio.thumb_image unless @portfolio.thumb_image.nil?  %>
  </div>
  <div class="col-md-6">
    <h1><%= @portfolio.title %></h1>

    <hr>

    <em><%= @portfolio.subtitle %></em>

    <hr>

    <p> <%= @portfolio.body %> </p>

    <hr>

    <%= link_to "Edit", edit_portfolioo_path(@portfolio) if logged_in?(:site_admin) %>
    <%= link_to "Delete", portfolioo_path(@portfolio), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
  </div>
 </div>
</div>