config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'tech-news', to: 'home#tech_news'

  resources :topics, only: [:index, :show]

  resources :blogs do
    member do
      post :toggle_status
    end
  end

  resources :portfolioos, except: [:index, :new, :show]
  get 'ror', to: 'portfolioos#ruby'
  get '/portfolio', to: 'portfolioos#index', as: 'portfolio'
  get '/portfolio/new', to: 'portfolioos#new', as: 'new_portfolio'
  get 'portfolio/:id', to: 'portfolioos#show', as: 'portfolio_show'

  devise_for :users, path: '', path_names: { sign_in: 'login',
  sign_out: 'logout', sign_up: 'register'}

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :blogs
  validates_presence_of :title
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  layout 'portfolio'
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    #passed to show page
    @blogs = @topic.blogs.all if logged_in?(:site_admin)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.erb
<div>
  <%= link_to topic.title, topic_path(topic) %>
</div>

app/views/topics/_topic_ruler.html.erb
<br>

app/views/topics/index.html.erb
<h1><%= render @topics %> </h1>

app/views/topics/show.html.erb
<h1><%= @topic.title %> </h1>

<!-- <%= render @blogs, spacer_template: 'topic_ruler'  %> -->
<div>
<p>
   <% @blogs.each do |blog| %>
    <td><%= blog.title.upcase %></td>
    <td> Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago </td>
    <td><%= blog.body %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</p>
</div>