config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'tech-news', to: 'home#tech_news'

  resources :topics, only: [:index, :show]

  resources :blogs do
    member do
      post :toggle_status
    end
  end

  resources :portfolioos, except: [:index, :new, :show]
  get 'ror', to: 'portfolioos#ruby'
  get '/portfolio', to: 'portfolioos#index', as: 'portfolio'
  get '/portfolio/new', to: 'portfolioos#new', as: 'new_portfolio'
  get 'portfolio/:id', to: 'portfolioos#show', as: 'portfolio_show'

  devise_for :users, path: '', path_names: { sign_in: 'login',
  sign_out: 'logout', sign_up: 'register'}

end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Stebs Portfolio", sticky:false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Stebs Portfolio", sticky:false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Stebs Portfolio", sticky:false) %>
<% end %>

app/views/shared/_portfolio_footer.html.erb
<footer class="blog-footer">
    <p> Build by Steven Gangano </p>

    <ul class="social-links">
      <li><a href="#"> <%= fa_icon "twitter" %> </a></li>
      <li><a href="#"> <%= fa_icon "facebook" %> </a></li>
      <li><a href="#"> <%= fa_icon "instagram" %> </a></li>
    </ul>
</footer>

app/views/shared/_portfolio_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:orange;">
  <a class="navbar-brand" href="#">Steven's Portfolio Page</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <div><%= link_to "Home", root_path, class:'nav-link'  %></div>
      </li>
      <li class="nav-item">
        <div><%= link_to "Blog", blogs_path, class:'nav-link' %></div>
      </li>
      <li class="nav-item">
        <div><%= link_to "Portfolio", portfolio_path, class:'nav-link' %></div>
      </li>
      <%= nav_helper 'nav-link', 'li' %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <div class="nav-link"> Hi, <%= current_user.first_name if current_user %> welcome to the page! </div>
      </li>
      <li><%= login_helper 'nav-link portfolio-nav-link' %></li>
    </ul>
  </div>
</nav>